version: "3.9" #optional

services: # Services names are used as DNS Hostnames
  app:
    build:
      context: .
      args:
        - DEV=true
      ports:
        - "8000:8000"
      volumess:
        - .:/app
      command: sh -c "python manage.py runserver 0.0.0.0:8000" #jalanan command ini ketika docker-compose up
      environment:
        - DB_HOST=db
        - DB_NAME=devdb
        - DB_USER=devuser
        - DB_PASSWORD=devpass
      depends_on:
        - db #ini untuk nunggu db jalan dulu baru jalanin app

    db:
      image: postgres:13 alpine
      environment:
        - POSTGRES_DB=devdb
        - POSTGRES_USER=devuser
        - POSTGRES_PASSWORD=devpass
      volumes:
        - dev-db-data:/var/lib/postgresql/data #ini untuk menyimpan data postgres di volume
  volumes:
    dev-db-data: #ini untuk membuat volume